sudo: false

language: c

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup --no-terminal

script:
  - STACK_YAML=stack.yaml stack test --no-terminal --skip-ghc-check
  - STACK_YAML=stack-7.10.yaml stack build --no-terminal --skip-ghc-check
  - STACK_YAML=stack-8.0.2.yaml stack build --no-terminal --skip-ghc-check
